use std::rc::Rc;

use dioxus::prelude::*;
use dioxus_field::{self as field, FieldContext, FieldMeta};
use dioxus_primitives::dioxus_attributes::attributes;
use dioxus_primitives::merge_attributes;

/// Whether [`Field`] emits the utilities that lay out its Compound parts.
///
/// daisyUI has no class for a Field's layout, so the default grid and spacing are
/// Tailwind utilities. [`FieldAppearance::None`] emits nothing so callers can
/// replace them without competing with utilities generated by the Registry
/// (ADR-0004).
#[derive(Copy, Clone, Debug, PartialEq, Default)]
#[non_exhaustive]
pub enum FieldAppearance {
    #[default]
    Default,
    None,
}

impl FieldAppearance {
    /// Every value of this axis, in the order the preview renders them.
    pub const ALL: &'static [Self] = &[Self::Default, Self::None];

    /// The Tailwind utilities for this value, as complete string literals so
    /// Tailwind's scanner can see them.
    pub const fn class(self) -> &'static str {
        match self {
            Self::Default => "grid min-w-0 gap-2",
            Self::None => "",
        }
    }
}

/// Whether [`FieldRow`] emits the utilities that lay a control out beside its
/// label.
///
/// daisyUI has no class for that row either, so the default is Tailwind
/// utilities. [`FieldRowAppearance::None`] emits nothing so callers can
/// replace them without competing with utilities generated by the Registry
/// (ADR-0004).
#[derive(Copy, Clone, Debug, PartialEq, Default)]
#[non_exhaustive]
pub enum FieldRowAppearance {
    #[default]
    Default,
    None,
}

impl FieldRowAppearance {
    /// Every value of this axis, in the order the preview renders them.
    pub const ALL: &'static [Self] = &[Self::Default, Self::None];

    /// The Tailwind utilities for this value, as complete string literals so
    /// Tailwind's scanner can see them.
    pub const fn class(self) -> &'static str {
        match self {
            Self::Default => "flex min-w-0 items-center gap-2",
            Self::None => "",
        }
    }
}

/// Whether [`FieldDescription`] emits shrink-safe prose wrapping utilities.
///
/// daisyUI's `label` class prevents wrapping. The default corrects that for a
/// description, while [`FieldDescriptionAppearance::None`] emits no utilities
/// so callers can replace the wrapping behavior without a utility tie
/// (ADR-0004).
#[derive(Copy, Clone, Debug, PartialEq, Default)]
#[non_exhaustive]
pub enum FieldDescriptionAppearance {
    #[default]
    Default,
    None,
}

impl FieldDescriptionAppearance {
    /// Every value of this axis, in the order the preview renders them.
    pub const ALL: &'static [Self] = &[Self::Default, Self::None];

    /// The Tailwind utilities for this value, as complete string literals so
    /// Tailwind's scanner can see them.
    pub const fn class(self) -> &'static str {
        match self {
            Self::Default => "min-w-0 whitespace-normal",
            Self::None => "",
        }
    }
}

/// Whether [`FieldError`] emits the utility that paints producer errors.
///
/// daisyUI has no independently usable error-message class. The default uses
/// its semantic error colour, and [`FieldErrorAppearance::None`] emits nothing
/// so a caller can supply different paint without fighting a utility tie
/// (ADR-0004).
#[derive(Copy, Clone, Debug, PartialEq, Default)]
#[non_exhaustive]
pub enum FieldErrorAppearance {
    #[default]
    Default,
    None,
}

impl FieldErrorAppearance {
    /// Every value of this axis, in the order the preview renders them.
    pub const ALL: &'static [Self] = &[Self::Default, Self::None];

    /// The Tailwind utility for this value, as a complete string literal so
    /// Tailwind's scanner can see it.
    pub const fn class(self) -> &'static str {
        match self {
            Self::Default => "text-error",
            Self::None => "",
        }
    }
}

/// One styled Field scope connecting a control to its Binding and metadata.
///
/// The wrapped `dioxus-field` provider owns context, metadata synchronization,
/// and focus registration. This wrapper only adds defeatable layout utilities.
/// Classes passed by the caller concatenate with those utilities; every other
/// caller attribute overrides them.
#[component]
pub fn Field(
    /// Whether to emit the default grid and spacing utilities.
    #[props(default)]
    appearance: FieldAppearance,
    /// The context supplied to the Field's control and Compound parts.
    #[props(into)]
    context: FieldContext,
    #[props(extends = GlobalAttributes)] attributes: Vec<Attribute>,
    children: Element,
) -> Element {
    let appearance = appearance.class();
    let base = attributes!(div {
        class: "{appearance}",
    });
    let merged = merge_attributes(vec![base, attributes]);

    rsx! {
        field::Field { context, attributes: merged, {children} }
    }
}

/// One row of a Field, laying a checkable control out beside its label.
///
/// A checkbox or a switch reads as its label's companion rather than as a
/// control stacked under a caption, and neither can be nested inside
/// [`FieldLabel`]: the Primitive renders a `button`, which a `label` does not
/// activate. This part is the row those two sit in. It carries no Field
/// mechanism of its own, so metadata still resolves from the surrounding
/// [`Field`]. Classes passed by the caller concatenate with its utilities;
/// every other caller attribute overrides them.
#[component]
pub fn FieldRow(
    /// Whether to emit the default row layout utilities.
    #[props(default)]
    appearance: FieldRowAppearance,
    #[props(extends = GlobalAttributes)] attributes: Vec<Attribute>,
    children: Element,
) -> Element {
    let appearance = appearance.class();
    let base = attributes!(div {
        class: "{appearance}",
    });
    let merged = merge_attributes(vec![base, attributes]);

    rsx! {
        div { ..merged, {children} }
    }
}

/// A Field caption associated with the control id declared by Field metadata.
///
/// The wrapped part resolves metadata from the Field Context and emits its
/// state attributes. Unlike the standalone Label Component, this part has no
/// `html_for` prop: its native `for` comes from `FieldMeta::id`.
#[component]
pub fn FieldLabel(
    /// Stable id registered with Field metadata for this part's lifetime.
    /// Omission uses the convention's generated fallback.
    #[props(default)]
    id: Option<String>,
    /// Explicit metadata, which wins over Field Context metadata.
    meta: Option<FieldMeta>,
    /// Explicit invalid state, which wins over metadata for this part.
    invalid: Option<bool>,
    /// Explicit disabled state, which wins over metadata for this part.
    disabled: Option<bool>,
    /// Explicit required state, which wins over metadata for this part.
    required: Option<bool>,
    #[props(extends = GlobalAttributes)] attributes: Vec<Attribute>,
    children: Element,
) -> Element {
    let base = attributes!(label { class: "label" });
    let merged = merge_attributes(vec![base, attributes]);

    rsx! {
        field::Label {
            id: id.map(Rc::from),
            meta,
            invalid,
            disabled,
            required,
            attributes: merged,
            {children}
        }
    }
}

/// Wrapping supporting text registered with the Field control's accessible
/// description.
///
/// The wrapped part resolves metadata, generates an id when none is supplied,
/// registers it for `aria-describedby`, and emits the metadata's state
/// attributes.
#[component]
pub fn FieldDescription(
    /// Whether to emit shrink-safe prose wrapping utilities.
    #[props(default)]
    appearance: FieldDescriptionAppearance,
    /// Explicit id for external references. Omission uses the convention's
    /// generated fallback.
    #[props(default)]
    id: Option<Rc<str>>,
    /// Explicit metadata, which wins over Field Context metadata.
    meta: Option<FieldMeta>,
    /// Explicit invalid state, which wins over metadata for this part.
    invalid: Option<bool>,
    /// Explicit disabled state, which wins over metadata for this part.
    disabled: Option<bool>,
    /// Explicit required state, which wins over metadata for this part.
    required: Option<bool>,
    #[props(extends = GlobalAttributes)] attributes: Vec<Attribute>,
    children: Element,
) -> Element {
    let appearance = appearance.class();
    let base = attributes!(div {
        class: "label {appearance}"
    });
    let merged = merge_attributes(vec![base, attributes]);

    rsx! {
        field::FieldDescription { id, meta, invalid, disabled, required, attributes: merged, {children} }
    }
}

/// Producer-formatted Field errors in an always-mounted polite live region.
///
/// The wrapped part generates an id when none is supplied, registers it for
/// `aria-errormessage`, reads error text from Field metadata, and renders
/// content while invalid. This wrapper only adds defeatable colour.
#[component]
pub fn FieldError(
    /// Whether to paint errors with the semantic error colour.
    #[props(default)]
    appearance: FieldErrorAppearance,
    /// Explicit id for external references. Omission uses the convention's
    /// generated fallback.
    #[props(default)]
    id: Option<Rc<str>>,
    /// Explicit metadata, which wins over Field Context metadata.
    meta: Option<FieldMeta>,
    /// Explicit invalid state, which wins over metadata for this part.
    invalid: Option<bool>,
    /// Explicit disabled state used by this part's state attributes.
    disabled: Option<bool>,
    /// Explicit required state used by this part's state attributes.
    required: Option<bool>,
    #[props(extends = GlobalAttributes)] attributes: Vec<Attribute>,
) -> Element {
    let appearance = appearance.class();
    let base = attributes!(div {
        class: "{appearance}",
    });
    let merged = merge_attributes(vec![base, attributes]);

    rsx! {
        field::FieldError { id, meta, invalid, disabled, required, attributes: merged }
    }
}
