use schemaform::{
    FindingVisibility, FindingVisibilityPolicy, FormDefinition, JsonPointer, RetrievalUri,
    SchemaResource, SubmissionOutcome,
    definition::{CompileError, DefinitionNodeKind, SemanticKind},
    form::{SubmissionBlocker, ValidationOutcomeView},
};
use serde_json::{Value, json};

fn root_schema() -> Value {
    json!({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://schemas.example/forms/root.json",
        "type": "object",
        "additionalProperties": false,
        "required": ["contact"],
        "properties": {
            "contact": {
                "$ref": "../shared/contact.json#contact",
                "properties": {
                    "name": { "minLength": 3 }
                }
            }
        }
    })
}

fn contact_resource(min_length: u64) -> Value {
    json!({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://schemas.example/shared/contact.json",
        "$defs": {
            "contact": {
                "$anchor": "contact",
                "type": "object",
                "title": "Contact",
                "additionalProperties": false,
                "required": ["name"],
                "properties": {
                    "name": {
                        "type": "string",
                        "title": "Name",
                        "minLength": min_length
                    }
                }
            }
        }
    })
}

fn compile(min_length: u64) -> Result<FormDefinition, CompileError> {
    FormDefinition::compiler(root_schema())
        .root_uri(uri("https://retrieval.example/root.json"))
        .resource(SchemaResource::new(
            uri("https://cdn.example/contact.json"),
            contact_resource(min_length),
        ))
        .compile()
}

fn uri(value: &str) -> RetrievalUri {
    RetrievalUri::parse(value).expect("the fixture URI should be absolute and fragment-free")
}

#[test]
fn caller_supplied_canonical_resource_and_anchor_compile_with_exact_locations() {
    let definition = compile(2).expect("the complete in-memory resource graph should compile");
    let repeated = compile(2).expect("the same resource graph should compile repeatedly");
    assert_eq!(definition.fingerprint(), repeated.fingerprint());

    let root = definition
        .node(definition.root())
        .expect("the root should exist");
    assert_eq!(
        root.schema_locations()
            .map(|location| (location.resource().as_str(), location.pointer().as_str()))
            .collect::<Vec<_>>(),
        [("https://schemas.example/forms/root.json", "")]
    );
    let contact = root
        .children()
        .next()
        .and_then(|identity| definition.node(identity))
        .expect("the anchored fixed object should exist");
    assert_eq!(contact.kind(), DefinitionNodeKind::AutoGeneratedLayout);
    assert_eq!(contact.semantic_kind(), Some(SemanticKind::FixedObject));
    assert_eq!(contact.binding().map(JsonPointer::as_str), Some("/contact"));
    assert_eq!(contact.label(), "Contact");

    let name = contact
        .children()
        .next()
        .and_then(|identity| definition.node(identity))
        .expect("the anchored nested control should exist");
    assert_eq!(name.kind(), DefinitionNodeKind::Control);
    assert_eq!(
        name.binding().map(JsonPointer::as_str),
        Some("/contact/name")
    );
    assert_eq!(
        name.schema_locations()
            .map(|location| (location.resource().as_str(), location.pointer().as_str()))
            .collect::<Vec<_>>(),
        [
            (
                "https://schemas.example/forms/root.json",
                "/properties/contact/properties/name",
            ),
            (
                "https://schemas.example/shared/contact.json",
                "/$defs/contact/properties/name",
            ),
        ]
    );
}

#[test]
fn anchored_resource_control_validates_edits_and_submits() {
    let definition = compile(3).expect("the complete in-memory resource graph should compile");
    let mut form = definition
        .form(json!({ "contact": { "name": "Ada" } }))
        .finding_visibility(FindingVisibilityPolicy::new(
            FindingVisibility::Immediate,
            FindingVisibility::TouchedOrSubmission,
        ))
        .build()
        .expect("the anchored form should be created");
    let contact = form
        .node(form.view().root())
        .and_then(|node| node.children().next())
        .expect("the fixed object should be instantiated");
    let name = form
        .node(contact)
        .and_then(|node| node.children().next())
        .expect("the nested control should be instantiated");

    form.user()
        .input_text(name, "Li")
        .expect("the nested control should accept text input");
    assert!(matches!(
        form.view().validation_outcome(),
        ValidationOutcomeView::Invalid { findings, .. }
            if findings.iter().any(|finding| {
                finding.code() == "minLength"
                    && finding.instance_location().as_str() == "/contact/name"
                    && finding.keyword_location().resource().as_str()
                        == "https://schemas.example/shared/contact.json"
                    && finding.keyword_location().pointer().as_str()
                        == "/$defs/contact/properties/name/minLength"
            })
    ));
    assert!(matches!(
        form.prepare_submission().outcome(),
        SubmissionOutcome::Blocked(blockers)
            if blockers.iter().any(|blocker| matches!(blocker, SubmissionBlocker::Validation(_)))
    ));

    form.user()
        .input_text(name, "Grace")
        .expect("the nested control should accept a correction");
    let prepared = form.prepare_submission();
    let SubmissionOutcome::Ready(snapshot) = prepared.outcome() else {
        panic!("the corrected anchored form should submit");
    };
    assert_eq!(
        snapshot.form_data(),
        &json!({ "contact": { "name": "Grace" } })
    );
}

#[test]
fn incomplete_resource_graph_fails_without_implicit_retrieval() {
    let error = FormDefinition::compiler(root_schema())
        .root_uri(uri("https://retrieval.example/root.json"))
        .compile()
        .err()
        .expect("a missing caller-supplied resource should fail compilation");
    assert!(matches!(
        error,
        CompileError::Qualification(schemaform::QualificationError::UnresolvedReference { .. })
    ));
}

#[test]
fn resource_semantics_participate_in_the_definition_fingerprint() {
    let short = compile(2).expect("the first complete graph should compile");
    let long = compile(4).expect("the changed complete graph should compile");
    assert_ne!(short.fingerprint(), long.fingerprint());
}

#[test]
fn unused_supplied_resources_do_not_change_the_definition_fingerprint() {
    let baseline = compile(2).expect("the referenced resource should compile");
    let with_unused = FormDefinition::compiler(root_schema())
        .root_uri(uri("https://retrieval.example/root.json"))
        .resource(SchemaResource::new(
            uri("https://cdn.example/contact.json"),
            contact_resource(2),
        ))
        .resource(SchemaResource::new(
            uri("https://cdn.example/unused.json"),
            json!({
                "$schema": "https://json-schema.org/draft/2020-12/schema",
                "$id": "https://schemas.example/unused.json",
                "type": "string"
            }),
        ))
        .compile()
        .expect("an unused valid resource should not affect compilation");

    assert_eq!(baseline.fingerprint(), with_unused.fingerprint());
}

#[test]
fn explicit_supplied_resource_dialect_takes_precedence_over_the_default() {
    let error = FormDefinition::compiler(root_schema())
        .default_dialect(schemaform::Dialect::Draft202012)
        .root_uri(uri("https://retrieval.example/root.json"))
        .resource(SchemaResource::new(
            uri("https://cdn.example/contact.json"),
            json!({
                "$schema": "http://json-schema.org/draft-07/schema#",
                "$id": "https://schemas.example/shared/contact.json",
                "$defs": {}
            }),
        ))
        .compile()
        .err()
        .expect("a supplied resource with another dialect should be rejected");
    assert!(matches!(
        error,
        CompileError::Qualification(schemaform::QualificationError::UnsupportedDialect { .. })
    ));
}

#[test]
fn ignored_additional_items_content_does_not_enter_the_resource_graph() {
    let definition = FormDefinition::compile(json!({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "type": "object",
        "properties": { "name": { "type": "string" } },
        "additionalItems": {
            "$schema": "http://json-schema.org/draft-07/schema#",
            "$id": "https://schemas.example/ignored.json",
            "$anchor": "ignored"
        }
    }))
    .expect("Draft 2020-12 treats additionalItems as an ignored annotation");

    assert!(definition.node(definition.root()).is_some());
}

#[test]
fn anchored_finding_locations_decode_uri_escaped_pointer_tokens() {
    let definition = FormDefinition::compiler(json!({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://schemas.example/forms/pricing.json",
        "type": "object",
        "properties": {
            "pricing": { "$ref": "../shared/pricing.json#pricing" }
        }
    }))
    .root_uri(uri("https://retrieval.example/pricing.json"))
    .resource(SchemaResource::new(
        uri("https://cdn.example/pricing.json"),
        json!({
            "$schema": "https://json-schema.org/draft/2020-12/schema",
            "$id": "https://schemas.example/shared/pricing.json",
            "$defs": {
                "pricing": {
                    "$anchor": "pricing",
                    "type": "object",
                    "properties": {
                        "unit price": { "type": "string", "minLength": 3 }
                    }
                }
            }
        }),
    ))
    .compile()
    .expect("the anchored resource should compile");
    let form = definition
        .create_form(json!({ "pricing": { "unit price": "Li" } }))
        .expect("the anchored form should be created");
    let view = form.view();
    let ValidationOutcomeView::Invalid { findings, .. } = view.validation_outcome() else {
        panic!("the short unit price should be invalid");
    };

    assert!(findings.iter().any(|finding| {
        finding.keyword_location().resource().as_str()
            == "https://schemas.example/shared/pricing.json"
            && finding.keyword_location().pointer().as_str()
                == "/$defs/pricing/properties/unit price/minLength"
    }));
}
