use schemaform::{
    CompileError, ExternalFinding, ExternalFindingBatch, FindingVisibility,
    FindingVisibilityPolicy, Form, FormDefinition, InstanceIdentity, ItemIdentity, JsonPointer,
    SubmissionOutcome,
    definition::{DefinitionNodeKind, SemanticKind},
    form::SubmissionBlocker,
};
use serde_json::json;

#[cfg(all(target_arch = "wasm32", target_os = "unknown"))]
wasm_bindgen_test::wasm_bindgen_test_configure!(run_in_browser);

#[cfg_attr(
    all(target_arch = "wasm32", target_os = "unknown"),
    wasm_bindgen_test::wasm_bindgen_test
)]
#[cfg_attr(not(all(target_arch = "wasm32", target_os = "unknown")), test)]
fn generated_fixed_object_item_template_edits_nested_rows_and_submits() {
    let definition = FormDefinition::compile(json!({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "type": "object",
        "additionalProperties": false,
        "required": ["people"],
        "properties": {
            "people": {
                "type": "array",
                "title": "People",
                "items": {
                    "type": "object",
                    "title": "Person",
                    "additionalProperties": false,
                    "required": ["name", "address"],
                    "properties": {
                        "name": {
                            "type": "string",
                            "title": "Name",
                            "minLength": 3
                        },
                        "address": {
                            "type": "object",
                            "title": "Address",
                            "additionalProperties": false,
                            "required": ["city"],
                            "properties": {
                                "city": {
                                    "type": "string",
                                    "title": "City",
                                    "minLength": 3
                                }
                            }
                        }
                    }
                }
            }
        }
    }))
    .expect("fixed-object array items should compile");

    let root = definition.node(definition.root()).unwrap();
    let array_id = root.children().next().expect("the array should exist");
    let array = definition.node(array_id).unwrap();
    assert_eq!(array.semantic_kind(), Some(SemanticKind::HomogeneousArray));
    assert_eq!(array.binding().map(JsonPointer::as_str), Some("/people"));

    let template_id = array
        .children()
        .next()
        .expect("the generated item template should exist");
    let template = definition.node(template_id).unwrap();
    assert_eq!(template.kind(), DefinitionNodeKind::AutoGeneratedLayout);
    assert_eq!(template.semantic_kind(), Some(SemanticKind::FixedObject));
    assert_eq!(template.binding().map(JsonPointer::as_str), Some(""));
    assert_eq!(template.label(), "Person");

    let template_children = template
        .children()
        .map(|id| definition.node(id).unwrap())
        .collect::<Vec<_>>();
    let name = template_children
        .iter()
        .find(|node| {
            node.binding()
                .is_some_and(|binding| binding.as_str() == "/name")
        })
        .expect("the relative name control should exist");
    let address = template_children
        .iter()
        .find(|node| {
            node.binding()
                .is_some_and(|binding| binding.as_str() == "/address")
        })
        .expect("the relative nested object should exist");
    let city = address
        .children()
        .next()
        .and_then(|id| definition.node(id))
        .expect("the relative city control should exist");
    assert_eq!(name.semantic_kind(), Some(SemanticKind::String));
    assert_eq!(
        city.binding().map(JsonPointer::as_str),
        Some("/address/city")
    );

    let duplicate = json!({ "name": "Ada", "address": { "city": "Rome" } });
    let mut form = definition
        .form(json!({ "people": [duplicate.clone(), duplicate] }))
        .finding_visibility(FindingVisibilityPolicy::new(
            FindingVisibility::Immediate,
            FindingVisibility::Immediate,
        ))
        .build()
        .unwrap();
    let array = node_with_binding(&form, "/people");
    let rows = form.node(array).unwrap().children().collect::<Vec<_>>();
    assert_eq!(rows.len(), 2);
    assert_ne!(
        rows[0], rows[1],
        "duplicate-valued rows need distinct identity"
    );
    assert_eq!(
        form.node(rows[0])
            .unwrap()
            .binding()
            .unwrap()
            .pointer()
            .as_str(),
        "/people/0"
    );
    assert_eq!(
        form.node(rows[1])
            .unwrap()
            .binding()
            .unwrap()
            .pointer()
            .as_str(),
        "/people/1"
    );

    let second_city = descendant_with_binding(&form, rows[1], "/people/1/address/city");
    form.user().input_text(second_city, "Li").unwrap();
    assert!(
        form.node(second_city)
            .unwrap()
            .validation_findings()
            .any(|finding| {
                finding.code() == "minLength"
                    && finding.instance_location().as_str() == "/people/1/address/city"
            })
    );
    form.user().input_text(second_city, "Paris").unwrap();

    let preparation = form.prepare_submission();
    let SubmissionOutcome::Ready(snapshot) = preparation.outcome() else {
        panic!("the corrected fixed-object rows should submit")
    };
    assert_eq!(
        snapshot.form_data(),
        &json!({
            "people": [
                { "name": "Ada", "address": { "city": "Rome" } },
                { "name": "Ada", "address": { "city": "Paris" } }
            ]
        })
    );
}

#[cfg_attr(
    all(target_arch = "wasm32", target_os = "unknown"),
    wasm_bindgen_test::wasm_bindgen_test
)]
#[cfg_attr(not(all(target_arch = "wasm32", target_os = "unknown")), test)]
fn duplicate_fixed_object_rows_keep_descendant_state_through_structural_commands() {
    let definition = FormDefinition::compile(json!({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "type": "object",
        "additionalProperties": false,
        "required": ["rows"],
        "properties": {
            "rows": {
                "type": "array",
                "items": {
                    "type": "object",
                    "additionalProperties": false,
                    "default": { "amount": 2, "address": { "city": "Seed" } },
                    "required": ["amount", "address"],
                    "properties": {
                        "amount": { "type": "number" },
                        "address": {
                            "type": "object",
                            "additionalProperties": false,
                            "required": ["city"],
                            "properties": {
                                "city": { "type": "string" }
                            }
                        }
                    }
                }
            }
        }
    }))
    .unwrap();
    let duplicate = json!({ "amount": 1, "address": { "city": "Rome" } });
    let mut form = definition
        .form(json!({ "rows": [duplicate.clone(), duplicate] }))
        .finding_visibility(FindingVisibilityPolicy::new(
            FindingVisibility::Immediate,
            FindingVisibility::Immediate,
        ))
        .build()
        .unwrap();
    let array = node_with_binding(&form, "/rows");
    let initial = row_instances(&form, array);
    let logical_row = initial[1];
    let amount = descendant_with_binding(&form, logical_row.0, "/rows/1/amount");
    let city = descendant_with_binding(&form, logical_row.0, "/rows/1/address/city");
    form.user().input_text(amount, "not a number").unwrap();
    form.user().blur(amount).unwrap();
    form.apply_external_findings(ExternalFindingBatch::new(
        "server",
        form.view().data_revision(),
        [ExternalFinding::blocking(
            "review-city",
            JsonPointer::parse("/rows/1/address/city").unwrap(),
            json!({}),
        )],
    ))
    .unwrap();

    let moved = form.user().move_item_up(array, logical_row.1).unwrap();
    assert_eq!(row_instances(&form, array), vec![logical_row, initial[0]]);
    let moved_amount = form
        .node(amount)
        .expect("the descendant identity should move");
    assert_eq!(
        moved_amount.binding().unwrap().pointer().as_str(),
        "/rows/0/amount"
    );
    assert_eq!(moved_amount.edit_buffer(), Some("not a number"));
    assert!(moved_amount.parse_blocker().is_some());
    assert!(moved_amount.is_touched());
    let moved_city = form.node(city).expect("the nested identity should move");
    assert_eq!(
        moved_city.binding().unwrap().pointer().as_str(),
        "/rows/0/address/city"
    );
    assert_eq!(
        moved_city
            .external_findings()
            .next()
            .expect("the descendant finding should follow its row")
            .1
            .instance_location()
            .as_str(),
        "/rows/0/address/city"
    );
    assert_transition_contains_row_subtree(&form, &moved, logical_row.0);
    assert_transition_contains_row_subtree(&form, &moved, initial[0].0);

    form.user().move_item_down(array, logical_row.1).unwrap();
    assert_eq!(
        form.node(amount)
            .unwrap()
            .binding()
            .unwrap()
            .pointer()
            .as_str(),
        "/rows/1/amount"
    );

    let inserted = form
        .user()
        .insert_item_before(array, logical_row.1)
        .unwrap();
    let after_insert = row_instances(&form, array);
    assert_eq!(after_insert[0], initial[0]);
    assert_eq!(after_insert[2], logical_row);
    assert_eq!(
        form.form_data()["rows"][1],
        json!({ "amount": 2, "address": { "city": "Seed" } })
    );
    assert_transition_contains_row_subtree(&form, &inserted, after_insert[1].0);
    assert_transition_contains_row_subtree(&form, &inserted, logical_row.0);
    assert_eq!(
        form.node(amount).unwrap().edit_buffer(),
        Some("not a number")
    );

    let removed = form.user().remove_item(array, after_insert[1].1).unwrap();
    assert!(
        removed
            .removed()
            .any(|identity| identity == after_insert[1].0)
    );
    assert_eq!(row_instances(&form, array), initial);
    assert_eq!(
        form.node(amount).unwrap().edit_buffer(),
        Some("not a number")
    );

    let appended = form.user().append_item(array).unwrap();
    let after_append = row_instances(&form, array);
    assert_transition_contains_row_subtree(&form, &appended, after_append[2].0);
    form.user().remove_item(array, after_append[2].1).unwrap();
    assert_eq!(row_instances(&form, array), initial);
}

#[cfg_attr(
    all(target_arch = "wasm32", target_os = "unknown"),
    wasm_bindgen_test::wasm_bindgen_test
)]
#[cfg_attr(not(all(target_arch = "wasm32", target_os = "unknown")), test)]
fn arrays_nested_in_fixed_object_items_are_capability_blocking_through_references() {
    for (items, keyword_location) in [
        (
            json!({
                "type": "object",
                "properties": { "nested": { "type": "array", "items": { "type": "string" } } }
            }),
            "/properties/rows/items/properties/nested",
        ),
        (
            json!({ "$ref": "#/$defs/row" }),
            "/$defs/row/properties/nested",
        ),
    ] {
        let schema = json!({
            "$schema": "https://json-schema.org/draft/2020-12/schema",
            "type": "object",
            "properties": { "rows": { "type": "array", "items": items } },
            "$defs": {
                "row": {
                    "type": "object",
                    "properties": {
                        "nested": { "type": "array", "items": { "type": "string" } }
                    }
                }
            }
        });
        let report = match FormDefinition::compile(schema.clone()) {
            Err(CompileError::Capability(report)) => report,
            Err(error) => panic!("unexpected compile error: {error}"),
            Ok(_) => panic!("nested arrays must not compile"),
        };
        let analysis = FormDefinition::compiler(schema.clone())
            .analyze()
            .expect("a nested array should remain a finite unsupported region");
        let repeated = FormDefinition::compiler(schema)
            .analyze()
            .expect("repeated nested-array analysis should be deterministic");
        assert_eq!(&report, analysis.capability_report());
        assert_eq!(analysis.capability_report(), repeated.capability_report());
        assert_eq!(
            analysis.definition().fingerprint(),
            repeated.definition().fingerprint()
        );
        let finding = report
            .findings()
            .find(|finding| finding.code() == "structure.array.nested")
            .expect("the nested-array finding should be reported");
        assert_eq!(finding.instance_location().as_str(), "/rows");
        assert_eq!(
            finding.keyword_location().pointer().as_str(),
            keyword_location
        );
        assert!(finding.is_blocking());

        let definition = analysis.into_parts().0;
        assert!(definition_contains_unsupported(&definition));
        let form_data = json!({ "rows": [{ "nested": ["preserved"] }] });
        let mut form = definition
            .create_form(form_data.clone())
            .expect("nested-array form data should remain constructible in lenient mode");
        assert!(matches!(
            form.prepare_submission().outcome(),
            SubmissionOutcome::Blocked(blockers)
                if blockers.iter().any(|blocker| matches!(
                    blocker,
                    SubmissionBlocker::Capability(finding)
                        if finding.code() == "structure.array.nested"
                ))
        ));
        assert_eq!(form.form_data(), &form_data);
    }
}

#[cfg_attr(
    all(target_arch = "wasm32", target_os = "unknown"),
    wasm_bindgen_test::wasm_bindgen_test
)]
#[cfg_attr(not(all(target_arch = "wasm32", target_os = "unknown")), test)]
fn fixed_object_array_append_uses_default_and_minimal_object_seeds() {
    let definition = FormDefinition::compile(json!({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "type": "object",
        "required": ["defaulted", "minimal"],
        "properties": {
            "defaulted": {
                "type": "array",
                "items": {
                    "type": "object",
                    "default": { "name": "New" },
                    "properties": { "name": { "type": "string" } }
                }
            },
            "minimal": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": { "name": { "type": "string" } }
                }
            }
        }
    }))
    .expect("both fixed-object item seed forms should compile");
    let mut form = definition
        .create_form(json!({ "defaulted": [], "minimal": [{}] }))
        .unwrap();
    let defaulted = node_with_binding(&form, "/defaulted");
    let minimal = node_with_binding(&form, "/minimal");
    let existing_minimal = row_instances(&form, minimal)[0].1;

    form.user().append_item(defaulted).unwrap();
    form.user()
        .insert_item_before(minimal, existing_minimal)
        .unwrap();

    assert_eq!(
        form.form_data(),
        &json!({ "defaulted": [{ "name": "New" }], "minimal": [{}, {}] })
    );
}

#[cfg_attr(
    all(target_arch = "wasm32", target_os = "unknown"),
    wasm_bindgen_test::wasm_bindgen_test
)]
#[cfg_attr(not(all(target_arch = "wasm32", target_os = "unknown")), test)]
fn fixed_object_item_choices_remain_selectable() {
    let definition = FormDefinition::compile(json!({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "type": "object",
        "properties": {
            "rows": {
                "type": "array",
                "items": {
                    "type": "object",
                    "required": ["status"],
                    "properties": {
                        "status": { "enum": ["new", "done"] }
                    }
                }
            }
        }
    }))
    .unwrap();
    let mut form = definition
        .create_form(json!({ "rows": [{ "status": "new" }] }))
        .unwrap();
    let status = node_with_binding(&form, "/rows/0/status");

    assert!(
        form.node(status)
            .unwrap()
            .allowed_operations()
            .can_set_value()
    );
    form.user().set_value(status, json!("done")).unwrap();
    assert_eq!(form.form_data(), &json!({ "rows": [{ "status": "done" }] }));
}

#[cfg_attr(
    all(target_arch = "wasm32", target_os = "unknown"),
    wasm_bindgen_test::wasm_bindgen_test
)]
#[cfg_attr(not(all(target_arch = "wasm32", target_os = "unknown")), test)]
fn incompatible_fixed_object_rows_can_be_replaced_with_the_template_seed() {
    let definition = FormDefinition::compile(json!({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "type": "object",
        "properties": {
            "rows": {
                "type": "array",
                "items": {
                    "type": "object",
                    "default": { "name": "New" },
                    "required": ["name"],
                    "properties": { "name": { "type": "string" } }
                }
            }
        }
    }))
    .unwrap();
    let mut form = definition.create_form(json!({ "rows": [7] })).unwrap();
    let array = node_with_binding(&form, "/rows");
    let row = form.node(array).unwrap().children().next().unwrap();
    let seed = form
        .node(row)
        .unwrap()
        .definition()
        .creation_seed()
        .cloned()
        .unwrap();

    assert!(
        form.node(row)
            .unwrap()
            .allowed_operations()
            .can_replace_value()
    );
    form.user().replace_value(row, seed).unwrap();
    assert_eq!(form.form_data(), &json!({ "rows": [{ "name": "New" }] }));
}

#[cfg_attr(
    all(target_arch = "wasm32", target_os = "unknown"),
    wasm_bindgen_test::wasm_bindgen_test
)]
#[cfg_attr(not(all(target_arch = "wasm32", target_os = "unknown")), test)]
fn reset_removes_every_post_baseline_fixed_object_item_instance() {
    let definition = FormDefinition::compile(json!({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "type": "object",
        "required": ["rows"],
        "properties": {
            "rows": {
                "type": "array",
                "items": {
                    "type": "object",
                    "default": { "name": "New", "address": { "city": "Seed" } },
                    "required": ["name", "address"],
                    "properties": {
                        "name": { "type": "string" },
                        "address": {
                            "type": "object",
                            "required": ["city"],
                            "properties": { "city": { "type": "string" } }
                        }
                    }
                }
            }
        }
    }))
    .unwrap();
    let baseline_data = json!({
        "rows": [{ "name": "Ada", "address": { "city": "Rome" } }]
    });
    let mut form = definition.create_form(baseline_data.clone()).unwrap();
    let array = node_with_binding(&form, "/rows");
    let baseline = row_instances(&form, array);
    form.user().append_item(array).unwrap();
    let appended = row_instances(&form, array)[1].0;
    let appended_subtree = subtree_identities(&form, appended);

    let transition = form.reset();

    assert_eq!(form.form_data(), &baseline_data);
    assert_eq!(row_instances(&form, array), baseline);
    let removed = transition.removed().collect::<Vec<_>>();
    for identity in appended_subtree {
        assert!(form.node(identity).is_none());
        assert!(removed.contains(&identity));
    }
}

#[cfg_attr(
    all(target_arch = "wasm32", target_os = "unknown"),
    wasm_bindgen_test::wasm_bindgen_test
)]
#[cfg_attr(not(all(target_arch = "wasm32", target_os = "unknown")), test)]
fn duplicate_fixed_object_lifecycle_restores_or_replaces_complete_identity_topology() {
    let definition = FormDefinition::compile(json!({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "type": "object",
        "required": ["rows"],
        "properties": {
            "rows": {
                "type": "array",
                "items": {
                    "type": "object",
                    "default": { "name": "same", "nested": { "label": "same" } },
                    "required": ["name", "nested"],
                    "properties": {
                        "name": { "type": "string" },
                        "nested": {
                            "type": "object",
                            "required": ["label"],
                            "properties": { "label": { "type": "string" } }
                        }
                    }
                }
            }
        }
    }))
    .unwrap();
    let duplicate = json!({ "name": "same", "nested": { "label": "same" } });
    let data = json!({ "rows": [duplicate.clone(), duplicate] });

    let mut reset_form = definition.create_form(data.clone()).unwrap();
    let reset_array = node_with_binding(&reset_form, "/rows");
    let baseline_rows = row_instances(&reset_form, reset_array);
    let baseline_subtrees = baseline_rows
        .iter()
        .map(|row| subtree_identities(&reset_form, row.0))
        .collect::<Vec<_>>();
    reset_form
        .user()
        .remove_item(reset_array, baseline_rows[0].1)
        .unwrap();
    reset_form.user().append_item(reset_array).unwrap();
    let post_baseline = row_instances(&reset_form, reset_array)[1].0;
    let post_baseline_subtree = subtree_identities(&reset_form, post_baseline);

    let reset = reset_form.reset();

    assert_eq!(row_instances(&reset_form, reset_array), baseline_rows);
    for (row, expected) in baseline_rows.iter().zip(baseline_subtrees) {
        assert_eq!(subtree_identities(&reset_form, row.0), expected);
    }
    for identity in post_baseline_subtree {
        assert!(reset_form.node(identity).is_none());
        assert!(reset.removed().any(|removed| removed == identity));
    }

    enum LifecycleChange {
        Reinitialize,
        Replace,
    }

    for operation in [LifecycleChange::Reinitialize, LifecycleChange::Replace] {
        let mut form = definition.create_form(data.clone()).unwrap();
        let array = node_with_binding(&form, "/rows");
        let before = row_instances(&form, array)
            .into_iter()
            .flat_map(|row| subtree_identities(&form, row.0))
            .collect::<Vec<_>>();
        let transition = match operation {
            LifecycleChange::Reinitialize => form.reinitialize(data.clone()).unwrap(),
            LifecycleChange::Replace => form
                .transact(|draft| {
                    draft.set(
                        &JsonPointer::parse("/rows").unwrap(),
                        json!([
                            { "name": "same", "nested": { "label": "same" } },
                            { "name": "changed", "nested": { "label": "same" } }
                        ]),
                    );
                })
                .unwrap(),
        };
        let after = row_instances(&form, array)
            .into_iter()
            .flat_map(|row| subtree_identities(&form, row.0))
            .collect::<Vec<_>>();

        assert!(after.iter().all(|identity| !before.contains(identity)));
        assert!(before.iter().all(|identity| form.node(*identity).is_none()));
        assert!(
            before
                .iter()
                .all(|identity| transition.removed().any(|removed| removed == *identity))
        );
        assert!(
            after
                .iter()
                .all(|identity| transition.changed().any(|changed| changed == *identity))
        );
    }
}

fn node_with_binding(form: &Form, binding: &str) -> InstanceIdentity {
    descendant_with_binding(form, form.view().root(), binding)
}

fn descendant_with_binding(form: &Form, root: InstanceIdentity, binding: &str) -> InstanceIdentity {
    let mut pending = vec![root];
    while let Some(identity) = pending.pop() {
        let node = form.node(identity).expect("the form node should exist");
        if node
            .binding()
            .is_some_and(|current| current.pointer().as_str() == binding)
        {
            return identity;
        }
        pending.extend(node.children());
    }
    panic!("the bound node should exist: {binding}")
}

fn row_instances(form: &Form, array: InstanceIdentity) -> Vec<(InstanceIdentity, ItemIdentity)> {
    form.node(array)
        .unwrap()
        .children()
        .map(|identity| {
            let item = form
                .node(identity)
                .unwrap()
                .binding()
                .unwrap()
                .item()
                .unwrap();
            (identity, item)
        })
        .collect()
}

fn assert_transition_contains_row_subtree(
    form: &Form,
    transition: &schemaform::Transition,
    row: InstanceIdentity,
) {
    let changed = transition.changed().collect::<Vec<_>>();
    let mut pending = vec![row];
    while let Some(identity) = pending.pop() {
        assert!(
            changed.contains(&identity),
            "row subtree identity was not changed"
        );
        pending.extend(form.node(identity).unwrap().children());
    }
}

fn subtree_identities(form: &Form, root: InstanceIdentity) -> Vec<InstanceIdentity> {
    let mut identities = Vec::new();
    let mut pending = vec![root];
    while let Some(identity) = pending.pop() {
        identities.push(identity);
        pending.extend(form.node(identity).unwrap().children());
    }
    identities
}

fn definition_contains_unsupported(definition: &FormDefinition) -> bool {
    let mut pending = vec![definition.root()];
    while let Some(identity) = pending.pop() {
        let node = definition.node(identity).unwrap();
        if node.kind() == DefinitionNodeKind::Unsupported {
            return true;
        }
        pending.extend(node.children());
    }
    false
}
