use schemaform::{
    FindingVisibility, FindingVisibilityPolicy, FormDefinition, InstanceIdentity,
    SubmissionOutcome,
    definition::{DefinitionNodeKind, SemanticKind},
};
use serde_json::json;

#[test]
fn generated_string_form_uses_the_public_facade_without_mutating_on_construction() {
    let definition = FormDefinition::compile(json!({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "type": "object",
        "additionalProperties": false,
        "required": ["name"],
        "properties": {
            "name": {
                "type": "string",
                "title": "Name"
            }
        }
    }))
    .expect("the trusted data schema should compile");

    let cloned_definition = definition.clone();
    let root = definition
        .node(definition.root())
        .expect("the generated root should exist");
    assert_eq!(root.kind(), DefinitionNodeKind::AutoGeneratedLayout);

    let children = root.children().collect::<Vec<_>>();
    assert_eq!(children.len(), 1);
    let control = definition
        .node(children[0])
        .expect("the generated string control should exist");
    assert_eq!(control.kind(), DefinitionNodeKind::Control);
    assert_eq!(control.semantic_kind(), Some(SemanticKind::String));
    assert_eq!(
        control.binding().map(|binding| binding.as_str()),
        Some("/name")
    );
    assert_eq!(control.label(), "Name");
    assert!(control.is_required());

    let initial_data = json!({ "name": "Ada" });
    let mut form = definition
        .create_form(initial_data.clone())
        .expect("the first owned form should be created");
    let second_form = cloned_definition
        .create_form(initial_data.clone())
        .expect("the reusable definition should create another form");

    assert_eq!(form.form_data(), &initial_data);
    assert_eq!(second_form.form_data(), &initial_data);
    assert_ne!(
        form.view().data_revision(),
        second_form.view().data_revision()
    );
    assert_ne!(
        form.view().state_revision(),
        second_form.view().state_revision()
    );

    let control_identity = form
        .node(form.view().root())
        .expect("the form root should exist")
        .children()
        .next()
        .expect("the generated control should be instantiated");
    assert!(second_form.node(control_identity).is_none());

    let transition = form
        .user()
        .input_text(control_identity, "Grace")
        .expect("the string control should accept text input");
    assert!(!transition.is_empty());
    assert_eq!(transition.changed().collect::<Vec<_>>(), [control_identity]);
    assert_eq!(form.form_data(), &json!({ "name": "Grace" }));

    let prepared = form.prepare_submission();
    let snapshot = match prepared.outcome() {
        SubmissionOutcome::Ready(snapshot) => snapshot.clone(),
        SubmissionOutcome::Blocked(_) => panic!("the string form should be submittable"),
    };
    assert_eq!(snapshot.form_data(), &json!({ "name": "Grace" }));

    form.user()
        .input_text(control_identity, "Lin")
        .expect("the form should remain editable after submission");
    assert_eq!(form.form_data(), &json!({ "name": "Lin" }));
    assert_eq!(snapshot.form_data(), &json!({ "name": "Grace" }));
}

#[test]
fn scalar_edit_transition_reports_opaque_revisions_and_only_the_changed_instance() {
    let definition = FormDefinition::compile(json!({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "type": "object",
        "additionalProperties": false,
        "required": ["first_name", "last_name"],
        "properties": {
            "first_name": { "type": "string", "title": "First name" },
            "last_name": { "type": "string", "title": "Last name" }
        }
    }))
    .expect("the trusted data schema should compile");
    let mut form = definition
        .create_form(json!({ "first_name": "Ada", "last_name": "Lovelace" }))
        .expect("the owned form should be created");
    let first_name = control_with_binding(&form, "/first_name");
    let last_name = control_with_binding(&form, "/last_name");
    let before_data = form.view().data_revision();
    let before_state = form.view().state_revision();

    let transition = form
        .user()
        .input_text(first_name, "Grace")
        .expect("the first-name control should accept text input");

    assert_eq!(transition.before_data_revision(), before_data);
    assert_eq!(transition.before_state_revision(), before_state);
    assert_eq!(
        transition.after_data_revision(),
        form.view().data_revision()
    );
    assert_eq!(
        transition.after_state_revision(),
        form.view().state_revision()
    );
    assert_ne!(
        transition.before_data_revision(),
        transition.after_data_revision()
    );
    assert_ne!(
        transition.before_state_revision(),
        transition.after_state_revision()
    );
    assert_eq!(transition.changed().collect::<Vec<_>>(), [first_name]);
    assert!(transition.removed().next().is_none());
    assert_eq!(
        form.node(last_name)
            .expect("the unrelated control should still exist")
            .display_text()
            .as_deref(),
        Some("Lovelace")
    );

    let no_op = form
        .user()
        .input_text(first_name, "Grace")
        .expect("repeating the accepted input should succeed");

    assert!(no_op.is_empty());
    assert_eq!(no_op.before_data_revision(), no_op.after_data_revision());
    assert_eq!(no_op.before_state_revision(), no_op.after_state_revision());
    assert!(no_op.changed().next().is_none());
    assert!(no_op.removed().next().is_none());
}

#[test]
fn scalar_edit_transition_includes_another_instance_when_its_visible_findings_change() {
    let definition = FormDefinition::compile(json!({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "type": "object",
        "additionalProperties": false,
        "required": ["first_name", "last_name"],
        "properties": {
            "first_name": { "type": "string", "title": "First name" },
            "last_name": { "type": "string", "title": "Last name" }
        },
        "if": {
            "properties": {
                "first_name": { "const": "Grace" }
            }
        },
        "then": {
            "properties": {
                "last_name": { "minLength": 8 }
            }
        }
    }))
    .expect("the trusted data schema should compile");
    let mut form = definition
        .form(json!({ "first_name": "Ada", "last_name": "Hopper" }))
        .finding_visibility(FindingVisibilityPolicy::new(
            FindingVisibility::Immediate,
            FindingVisibility::TouchedOrSubmission,
        ))
        .build()
        .expect("the owned form should be created");
    let first_name = control_with_binding(&form, "/first_name");
    let last_name = control_with_binding(&form, "/last_name");
    assert_eq!(
        form.node(last_name)
            .expect("the last-name control should exist")
            .validation_findings()
            .count(),
        0
    );

    let transition = form
        .user()
        .input_text(first_name, "Grace")
        .expect("the first-name control should accept text input");

    assert_eq!(
        transition.changed().collect::<Vec<_>>(),
        [first_name, last_name]
    );
    let last_name_node = form
        .node(last_name)
        .expect("the last-name control should exist");
    let findings = last_name_node.validation_findings().collect::<Vec<_>>();
    assert_eq!(findings.len(), 1);
    assert_eq!(findings[0].code(), "minLength");
}

fn control_with_binding(form: &schemaform::Form, binding: &str) -> InstanceIdentity {
    let root = form.view().root();
    form.node(root)
        .expect("the form root should exist")
        .children()
        .find(|identity| {
            form.node(*identity)
                .and_then(|node| node.binding().map(|binding| binding.pointer().clone()))
                .is_some_and(|pointer| pointer.as_str() == binding)
        })
        .expect("the bound control should exist")
}

fn assert_public_traits()
where
    FormDefinition: Clone + Send + Sync,
    schemaform::Form: Send,
    schemaform::SubmissionSnapshot: Clone + Send + Sync,
    schemaform::Transition: Send + Sync,
{
}

#[test]
fn public_facade_has_the_accepted_threading_contract() {
    assert_public_traits();
}

#[test]
fn definition_fingerprints_frame_variable_length_semantics() {
    let left = FormDefinition::compile(json!({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "type": "object",
        "properties": {
            "a": { "type": "string", "title": "\u{0}b" }
        }
    }))
    .expect("the first data schema should compile");
    let right = FormDefinition::compile(json!({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "type": "object",
        "properties": {
            "a\u{0}": { "type": "string", "title": "b" }
        }
    }))
    .expect("the second data schema should compile");

    assert_ne!(left.fingerprint(), right.fingerprint());
}
