use schemaform::{
    FindingVisibility, FindingVisibilityPolicy, FormDefinition, JsonPointer, RetrievalUri,
    SubmissionOutcome,
    definition::{DefinitionNodeKind, SemanticKind},
    form::{SubmissionBlocker, ValidationOutcomeView},
};
use serde_json::{Value, json};

fn nested_local_reference_schema() -> Value {
    json!({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "urn:schemaform:test:nested-local-ref",
        "type": "object",
        "additionalProperties": false,
        "required": ["contact"],
        "properties": {
            "contact": {
                "$ref": "#/$defs/contact",
                "properties": {
                    "name": { "minLength": 3 }
                }
            }
        },
        "$defs": {
            "contact": {
                "type": "object",
                "title": "Contact",
                "additionalProperties": false,
                "required": ["name"],
                "properties": {
                    "name": { "type": "string", "title": "Name" }
                }
            }
        }
    })
}

#[test]
fn local_reference_and_its_siblings_compile_to_a_located_nested_definition() {
    let definition = FormDefinition::compile(nested_local_reference_schema())
        .expect("the local reference should compile");
    let repeated = FormDefinition::compile(nested_local_reference_schema())
        .expect("recompilation should succeed");
    assert_eq!(definition.fingerprint(), repeated.fingerprint());

    let root = definition
        .node(definition.root())
        .expect("the generated root should exist");
    let repeated_root = repeated
        .node(repeated.root())
        .expect("the repeated root should exist");
    assert_eq!(root.kind(), DefinitionNodeKind::AutoGeneratedLayout);
    assert_eq!(
        root.children().collect::<Vec<_>>(),
        repeated_root.children().collect::<Vec<_>>()
    );

    let contact_id = root
        .children()
        .next()
        .expect("the nested fixed object should exist");
    let contact = definition
        .node(contact_id)
        .expect("the nested fixed object should be addressable");
    assert_eq!(contact.kind(), DefinitionNodeKind::AutoGeneratedLayout);
    assert_eq!(contact.semantic_kind(), Some(SemanticKind::FixedObject));
    assert_eq!(contact.binding().map(JsonPointer::as_str), Some("/contact"));
    assert_eq!(contact.label(), "Contact");
    assert!(contact.is_required());

    let name_id = contact
        .children()
        .next()
        .expect("the nested string control should exist");
    let name = definition
        .node(name_id)
        .expect("the nested string control should be addressable");
    assert_eq!(name.kind(), DefinitionNodeKind::Control);
    assert_eq!(name.semantic_kind(), Some(SemanticKind::String));
    assert_eq!(
        name.binding().map(JsonPointer::as_str),
        Some("/contact/name")
    );
    assert_eq!(name.label(), "Name");
    assert!(name.is_required());
    assert_eq!(
        name.schema_locations()
            .map(|location| (location.resource().as_str(), location.pointer().as_str(),))
            .collect::<Vec<_>>(),
        [
            (
                "urn:schemaform:test:nested-local-ref",
                "/$defs/contact/properties/name",
            ),
            (
                "urn:schemaform:test:nested-local-ref",
                "/properties/contact/properties/name",
            ),
        ]
    );
    assert_eq!(
        name_id,
        repeated
            .node(contact_id)
            .unwrap()
            .children()
            .next()
            .unwrap()
    );
}

#[test]
fn local_reference_json_pointer_fragments_are_uri_decoded() {
    let definition = FormDefinition::compile(json!({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "type": "object",
        "properties": {
            "contact": { "$ref": "#/$defs/contact%20info" }
        },
        "$defs": {
            "contact info": {
                "type": "object",
                "properties": {
                    "email": { "type": "string" }
                }
            }
        }
    }))
    .expect("the percent-encoded local JSON Pointer should compile");
    let contact = definition
        .node(definition.root())
        .expect("the root should exist")
        .children()
        .next()
        .and_then(|identity| definition.node(identity))
        .expect("the nested fixed object should exist");
    let email = contact
        .children()
        .next()
        .and_then(|identity| definition.node(identity))
        .expect("the nested control should exist");

    assert_eq!(
        email.binding().map(JsonPointer::as_str),
        Some("/contact/email")
    );
    assert!(
        email.schema_locations().any(|location| {
            location.pointer().as_str() == "/$defs/contact info/properties/email"
        })
    );
}

#[test]
fn nested_control_edits_validate_and_submit_through_the_public_facade() {
    let definition = FormDefinition::compiler(nested_local_reference_schema())
        .root_uri(
            RetrievalUri::parse("urn:schemaform:test:retrieval")
                .expect("the retrieval URI should be valid"),
        )
        .compile()
        .expect("the local reference should compile");
    let mut form = definition
        .form(json!({ "contact": { "name": "Ada" } }))
        .finding_visibility(FindingVisibilityPolicy::new(
            FindingVisibility::Immediate,
            FindingVisibility::TouchedOrSubmission,
        ))
        .build()
        .expect("the nested form should be created");
    let contact = form
        .node(form.view().root())
        .expect("the form root should exist")
        .children()
        .next()
        .expect("the fixed object should be instantiated");
    let name = form
        .node(contact)
        .expect("the fixed object should exist")
        .children()
        .next()
        .expect("the nested control should be instantiated");

    form.user()
        .input_text(name, "Li")
        .expect("the nested control should accept text input");
    assert_eq!(form.form_data(), &json!({ "contact": { "name": "Li" } }));
    assert!(matches!(
        form.view().validation_outcome(),
        ValidationOutcomeView::Invalid { findings, .. }
            if findings.iter().any(|finding| {
                finding.code() == "minLength"
                    && finding.instance_location().as_str() == "/contact/name"
            })
    ));
    assert!(matches!(
        form.prepare_submission().outcome(),
        SubmissionOutcome::Blocked(blockers)
            if blockers.iter().any(|blocker| matches!(blocker, SubmissionBlocker::Validation(_)))
    ));

    form.user()
        .input_text(name, "Grace")
        .expect("the nested control should accept a correction");
    let prepared = form.prepare_submission();
    let snapshot = match prepared.outcome() {
        SubmissionOutcome::Ready(snapshot) => snapshot,
        SubmissionOutcome::Blocked(_) => panic!("the corrected nested form should submit"),
    };
    assert_eq!(
        snapshot.form_data(),
        &json!({ "contact": { "name": "Grace" } })
    );
}

#[test]
fn fixed_object_findings_are_observable_on_the_group_instance() {
    let definition = FormDefinition::compile(nested_local_reference_schema())
        .expect("the local reference should compile");
    let mut form = definition
        .create_form(json!({ "contact": {} }))
        .expect("the incomplete nested form should be created");
    let contact = form
        .node(form.view().root())
        .expect("the form root should exist")
        .children()
        .next()
        .expect("the fixed object should be instantiated");
    assert_eq!(
        form.node(contact)
            .expect("the fixed object should exist")
            .validation_findings()
            .count(),
        0,
        "default visibility should hide the finding before submission"
    );

    let preparation = form.prepare_submission();
    assert!(matches!(
        preparation.outcome(),
        SubmissionOutcome::Blocked(blockers)
            if blockers.iter().any(|blocker| matches!(blocker, SubmissionBlocker::Validation(_)))
    ));
    assert!(
        preparation
            .transition()
            .changed()
            .any(|identity| identity == contact)
    );
    let contact_node = form.node(contact).expect("the fixed object should exist");
    let findings = contact_node.validation_findings().collect::<Vec<_>>();
    assert_eq!(findings.len(), 1);
    assert_eq!(findings[0].code(), "required");
    assert_eq!(findings[0].instance_location().as_str(), "/contact");
}
