name = "demo"
engineVersion = "v1.0.0"
runtime.source = "dang"
include = ["!.devenv", "!.wrangler", "!build", "!dist", "!node_modules", "!target", "!e2e/node_modules", "!e2e/artifacts"]

[[dependencies]]
name = "dioxus"
source = "github.com/sagikazarmark/daggerverse-beta/dioxus"

[[dependencies]]
name = "worker-build"
source = "github.com/sagikazarmark/daggerverse-beta/worker-build"

